### ISSUE TITLE
AppleFmt Version error

### ISSUE THREAD

**Issue by baiyidjp** [kstenerud/KSCrash#529]
https://github.com/kstenerud/KSCrash/blob/8137c4990363b0ac7db5c11a48407c8713b6e1ff/Sources/KSCrashFilters/KSCrashReportFilterAppleFmt.m#L444C1-L445C78

shortVersion and bundleVersion are written inversely, Apple format should be 1.0.0 (10001), but is 10001 (1.0.0)

**Comment by GLinnik21** [comment]
Hi!
The issue you've pointed out is due to Apple changing its format. This change was introduced to conform to Apple's format in #277. I can see that they now use the `ver.si.on (build)` format, although they haven't updated their [documentation](https://developer.apple.com/documentation/xcode/examining-the-fields-in-a-crash-report#Header) yet. Despite this, I think it's worth fixing.

As we're getting ready version 2.0, If you have the time, we'd greatly appreciate if you could contribute a fix for this
