### ISSUE TITLE
how can I get the crash context and write other logs?

### ISSUE THREAD

**Issue by samhuangszu1** [kstenerud/KSCrash#537]

**Comment by GLinnik21** [comment]
Hi!
To add crash context and include additional information in your crash reports, use the `userInfo` property provided by KSCrash:

```swift
KSCrash.shared.userInfo = [
    "custom_key": "custom_value",
    "user_id": getCurrentUserId(),
    "app_state": getCurrentAppState(),
    "log_file_path": getLogFilePath()
]
```

This allows you to include any JSON-safe data that might be useful for understanding the crash context. For actual logging, it's recommended to use a separate logging system and include the log file path in `userInfo` rather than implementing logging within KSCrash itself.
