### ISSUE TITLE
Missing ["diagnosis"] key in the crash report information

### ISSUE THREAD

**Issue by avjiang** [kstenerud/KSCrash#595]
### Describe the bug

Previously before the version `rc-2`, most of the crashes captured, will have diagnosis info on what is going on and what are the exceptions, however after upgrading to `rc-2`, the whole structure changed and the framework did not capture anything useful from crash occured. After upgrading to `rc-2`, there are some API breaking changes and I managed to migrate to the new version.

Is there anything I missed out? 
Currently it is hard to identify what are the changes from each version as there is no changelogs. Can anyone please help?

Version
KSCrash `pod 'KSCrash', '2.0.0-rc.2'`
XCode 16
macOS Sequioa 15.1

Code snippets

```swift

        // AppDelegate.swift
        let kCrashInstallation = KSCrash.shared
        let config = KSCrashConfiguration()
        config.deadlockWatchdogInterval = 0
        config.reportStoreConfiguration.maxReportCount = 5
        config.monitors = [.all]
        
        do {
            try kCrashInstallation.install(with: config)
        }
        catch {}
        
        // Other file
        var allCrashReports = [CrashReportDictionary]()
        let kCrashInstallation = KSCrash.shared
        let crashReportFilterJSONEncode = CrashReportFilterJSONEncode()
        
        if let unsentReports = kCrashInstallation.reportStore?.reportIDs {
            if unsentReports.count > 0 {
                for reportID in unsentReports {
                    if let dictionaryReport = kCrashInstallation.reportStore?.report(for: reportID.int64Value) {
                        allCrashReports.append(dictionaryReport)
                    }
                }
            }
            crashReportFilterJSONEncode.filterReports(allCrashReports) { filteredReports, error in
                if filteredReports != nil {
                    for case let (index,  report as CrashReportData) in filteredReports!.enumerated() {
                        if report.isKind(of: CrashReportData.self) {
                            do {
                                let json = try JSONSerialization.jsonObject(with: report.value, options: [])
                                if let jsonObject = json as? NSDictionary {
                                    if let crashObject = jsonObject["crash"] as? NSDictionary {
                                        if let crashDiagnosis = crashObject["diagnosis"] {
                                            crashInfo = "\(crashDiagnosis)\n"
                                        }
                                        else {
                                            if let exceptionName = (crashObject as NSDictionary).value(forKeyPath: "error.mach.exception_name") {
                                                crashInfo = "Exception name - \(exceptionName)\n"
                                            }
                                        }
                                    }
                                    if let systemObject = jsonObject["system"] as? NSDictionary {
                                        appVersion = "App Version \(systemObject["CFBundleShortVersionString"] ?? "UNAVAILABLE")(\(systemObject["CFBundleVersion"] ?? "UNAVAILABLE")) \n"
                                        buildVersion += "OS \(systemObject["system_version"] ?? "UNAVAILABLE")"
                                    }
                                }
                            }
                            catch {
                                logger.error("KCrash JSONSerialization failed")
                            }
                        }
                    }
                }
            }
        }

```

### Steps to reproduce

1. Just trigger any crash

### KSCrash version

rc-2

### Operating System

iOS

### OS version

iOS 17 - 18

### Xcode version

16.1

**Comment by GLinnik21** [comment]
Hi @avjiang!
Thanks for the details. Here is the main suggestion to help address your issue:

**Diagnosis Missing**: The missing diagnosis information is likely due to configuration changes. The `KSCrashReportFilterDoctor` is now a filter that needs to be explicitly applied. To include diagnosis information, make sure to use it like any other filter. You can check the logic for the diagnosis filter [here](https://github.com/kstenerud/KSCrash/blob/e62b01179f951ffa6670af186b21f00657a92557/Sources/KSCrashFilters/KSCrashReportFilterDoctor.m#L57-L69).

Here are some additional recommendations:

1. **Release Version**: You're currently using `rc-2`, which might be causing some issues. I suggest trying the latest version `rc-7`, which can be found [here](https://github.com/kstenerud/KSCrash/releases/tag/2.0.0-rc.7). The newer release may contain fixes for the problems you're experiencing with diagnosis data not being captured.

2. **Changelog**: You mentioned having trouble identifying changes between versions. There is a changelog available on the [releases page](https://github.com/kstenerud/KSCrash/releases), which should help clarify what has changed and guide your migration.

3. **Migration Guide**: It sounds like you're having trouble with the API changes after upgrading to `rc-2`. The report structure itself hasn't changed much, with only some new fields being added. The breaking changes are mainly in the API, and you can find more details in the migration guide [here](https://github.com/kstenerud/KSCrash/wiki/Migration-Guide-for-KSCrash-1.x-to-2.0). Reviewing this guide should help ensure you've accounted for all necessary changes.

4. **Field Names**: To avoid any typos or issues with renamed fields, I recommend referring to the field names in the header file [KSCrashReportFields.h](https://github.com/kstenerud/KSCrash/blob/master/Sources/KSCrashRecording/include/KSCrashReportFields.h). This will help maintain consistency in your crash report handling.

Let me know if these suggestions help resolve your issue, or if you need more detailed assistance with the migration.

**Comment by avjiang** [comment]
hi @GLinnik21 !
Thank you so much for the information! Really appreciate it. I will try to adjust the things following what you have mentioned. Will temporarily close this issue for now. 

Cheers!
