### ISSUE TITLE
Send crash report in realtime(as opposed to next launch)

### ISSUE THREAD

**Issue by mlake** [kstenerud/KSCrash#83]
Hi - thanks for all your hard work creating a comprehensive crash library...we notice that some other commercial reporting tools (ie. BugSnag 3.x) would send crash reports in realtime as the app crashes, as opposed to sending reports on the next launch.

Any reason why KSCrash can not(or should not) be modified to write reports directly over the network vs. waiting until the next launch?

Thanks,
Michael Lake
WillowTree Apps

**Comment by felix-dumit** [comment]
Hi,

I don't need to send the report to any external place. 
I just want to be able to write the crash log to a file on disk at the time it crashes. I'm struggling on how to do that with the provided `KSCrashReportWriter* writer` on the crash callback.


Any help is much appreciated.

Thanks.

**Comment by kstenerud** [comment]
It already writes everything about the crash to disk at crash time, to

`<NSCachesDirectory>/KSCrashReports/<App Name>/<App Name>-CrashReport-<UUID>.json`

In the simulator, this will resolve to something like

`<HOME>/Library/Developer/CoreSimulator/Devices/B0E4A69F-4F44-4CAA-8E2C-2005FF55387F/data/Containers/Data/Application/F665DA34-5B6B-4DB3-A1F2-AD324B91CE60/Library/Caches/KSCrashReports/Simple-Example/Simple-Example-CrashReport-25F0C8BD-6E77-406C-868C-FC1656C1F81B.json`

The `KSCrashReportWriter` object is a JSON writer that will add anything you tell it to the user section of the above JSON file that it is creating. You call it like so:

    writer->addBooleanElement(writer, "some_bool_value", false);

Which creates an entry in the JSON file:

    some_bool_value: false

If you want to write in some format other than JSON, you'll have to open your own file and write to it.

**Beware**: any buffered IO calls like `fopen`, `fwrite`, and `fprintf` are not async-safe, and thus can lock up everything if the app crashes in certain ways. `open`, `close`, `read`, and `write` are OK, but they require a lot of hand holding because they are so low level by comparison. You can take a look at `KSFileUtils` to see how I'm using them.
